//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodas.Model.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class agendaServicio
    {
        public int id { get; set; }
        public int idAgenda { get; set; }
        public int idServicio { get; set; }
    
        public virtual Agenda Agenda { get; set; }
        public virtual C_Servicios C_Servicios { get; set; }
    }
}
