//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodas.Model.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agenda()
        {
            this.agendaServicio = new HashSet<agendaServicio>();
        }
    
        public int id { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaEvento { get; set; }
        public int idEjecutivo { get; set; }
        public Nullable<int> idCordinadora { get; set; }
        public Nullable<System.DateTime> fechaConfirmacion { get; set; }
        public Nullable<int> idLugarCeremonia { get; set; }
        public Nullable<int> idLugarCena { get; set; }
        public Nullable<int> idTipoCeremonia { get; set; }
        public Nullable<int> idTipoEvento { get; set; }
        public Nullable<int> idHoraEvento { get; set; }
        public Nullable<int> idhotel { get; set; }
        public string reserva { get; set; }
        public string bookingreference { get; set; }
        public Nullable<int> Pax { get; set; }
        public string correoAgencia { get; set; }
        public Nullable<int> idStatus { get; set; }
        public Nullable<int> idPaquete { get; set; }
        public Nullable<int> idCliente { get; set; }
    
        public virtual C_Clientes C_Clientes { get; set; }
        public virtual C_Estados C_Estados { get; set; }
        public virtual C_Hoteles C_Hoteles { get; set; }
        public virtual C_Lugares C_Lugares { get; set; }
        public virtual C_Lugares C_Lugares1 { get; set; }
        public virtual C_Paquetes C_Paquetes { get; set; }
        public virtual C_tiposEvento C_tiposEvento { get; set; }
        public virtual C_Usuarios C_Usuarios { get; set; }
        public virtual C_Usuarios C_Usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agendaServicio> agendaServicio { get; set; }
    }
}
