//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodas.Model.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BodasEntities : DbContext
    {
        public BodasEntities()
            : base("name=BodasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agenda> Agenda { get; set; }
        public virtual DbSet<agendaServicio> agendaServicio { get; set; }
        public virtual DbSet<C_Agencia> C_Agencia { get; set; }
        public virtual DbSet<C_Clientes> C_Clientes { get; set; }
        public virtual DbSet<C_Estados> C_Estados { get; set; }
        public virtual DbSet<C_Horarios> C_Horarios { get; set; }
        public virtual DbSet<C_Hoteles> C_Hoteles { get; set; }
        public virtual DbSet<C_Lugares> C_Lugares { get; set; }
        public virtual DbSet<C_Menu> C_Menu { get; set; }
        public virtual DbSet<C_Moneda> C_Moneda { get; set; }
        public virtual DbSet<C_Paquetes> C_Paquetes { get; set; }
        public virtual DbSet<C_Preguntas> C_Preguntas { get; set; }
        public virtual DbSet<C_Roles> C_Roles { get; set; }
        public virtual DbSet<C_Servicios> C_Servicios { get; set; }
        public virtual DbSet<C_Submenu> C_Submenu { get; set; }
        public virtual DbSet<C_tiposEvento> C_tiposEvento { get; set; }
        public virtual DbSet<C_Usuarios> C_Usuarios { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<nombreClientes> nombreClientes { get; set; }
        public virtual DbSet<paqueteServicio> paqueteServicio { get; set; }
        public virtual DbSet<preguntaRespuesta> preguntaRespuesta { get; set; }
        public virtual DbSet<C_Permisos> C_Permisos { get; set; }
    }
}
