//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodas.Model.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Permisos
    {
        public int id { get; set; }
        public string name { get; set; }
        public int idSubmenu { get; set; }
        public int idRol { get; set; }
    
        public virtual C_Roles C_Roles { get; set; }
        public virtual C_Submenu C_Submenu { get; set; }
    }
}
