//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodas.Model.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Servicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Servicios()
        {
            this.agendaServicio = new HashSet<agendaServicio>();
            this.paqueteServicio = new HashSet<paqueteServicio>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public decimal precio { get; set; }
        public string nota { get; set; }
        public int idMoneda { get; set; }
        public int idHotel { get; set; }
        public bool status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agendaServicio> agendaServicio { get; set; }
        public virtual C_Hoteles C_Hoteles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paqueteServicio> paqueteServicio { get; set; }
    }
}
