//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodas.Model.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string tabla { get; set; }
        public string columna { get; set; }
        public string valorO { get; set; }
        public string valorN { get; set; }
        public int idusuario { get; set; }
    
        public virtual C_Usuarios C_Usuarios { get; set; }
    }
}
